language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache

php:
    - 7.2

env:
    - ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=~7.1 TESTBENCH_VERSION=~3.8
    - ILLUMINATE_VERSION=6.0.* PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=~4.0
    - ILLUMINATE_VERSION=6.1.* PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=~4.0
    - ILLUMINATE_VERSION=6.2.* PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=~4.0
    - ILLUMINATE_VERSION=6.3.* PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=~4.0
    - ILLUMINATE_VERSION=6.4.* PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=~4.0
    - ILLUMINATE_VERSION=6.5.* PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=~4.0
    - ILLUMINATE_VERSION=6.6.* PHPUNIT_VERSION=~8.0 TESTBENCH_VERSION=~4.0

matrix:
    exclude:

before_install:
    - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
    - phpenv config-rm xdebug.ini
    - composer global require hirak/prestissimo --update-no-dev
    - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist
    - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --prefer-dist
    - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist

install: travis_retry composer install --no-interaction --prefer-dist

before_script: phpenv config-add ~/xdebug.ini

script: vendor/bin/phpunit

after_success: sh -c "if [ ! -z ${COVERAGE+x} ]; then php vendor/bin/coveralls; fi"

notifications:
    email: false
